version: "3.9"

services:
  db:
    image: mysql:8.4
    restart: unless-stopped
    environment:
      # Docker va injecter les valeurs définies dans le fichier .env
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
    ports:
      - "3330:3306"
    volumes:
      - sio:/var/lib/mysql
      - ./docker/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - sio

  phpmyadmin:
    image: phpmyadmin:latest
    restart: unless-stopped
    depends_on:
      - db
    environment:
      PMA_HOST: ${DB_HOST} # Utilise l'alias DNS défini dans l'environnement
      UPLOAD_LIMIT: 256M
    ports:
      - "8010:80"
    networks:
      - sio

volumes:
  sio:

networks:
  sio:
    driver: bridge